name: aplikasi_pemesanan_travel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.6.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.2
  geolocator: ^9.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  getwidget: ^3.1.1
  google_maps_flutter: ^2.3.0
  icons_plus: ^4.0.0
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  lottie: ^2.3.2
  pinput: ^2.2.31
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  webview_flutter: ^4.2.2

flutter_icons:
  image_path: "assets/logo/logo.png"
  android: true

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/logo/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 900
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 100
  uses-material-design: true
